#!/bin/sh
#
# Example init script for htpd

case "$1" in
  start)
    echo -n "Starting htpd..."
    /usr/local/htp/sbin/htpd
    echo
    ;;
  stop)
    echo -n "Shutting down htpd..."
    kill `cat /var/run/htpd.pid`
    echo
    rm -f /var/run/htpd.pid
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit 0
